Repository NOAA-OWP/DMOD, pull requests merged in 2022-01, with the labels that each got.

#98 Update Documentation On Subsetting CLI Tool
  doc/SUBSETTING_CLI_TOOL.md
Labels: bug, documentation

#97 Data request serivce
  python/lib/modeldata/dmod/modeldata/__init__.py
  python/lib/modeldata/dmod/modeldata/_version.py
  python/lib/modeldata/dmod/modeldata/datarequest/__init__.py
  python/lib/modeldata/dmod/modeldata/datarequest/data_request_definition.py
  python/lib/modeldata/dmod/modeldata/datarequest/data_request_handler.py
  python/lib/modeldata/dmod/modeldata/datarequest/data_request_reader.py
  python/lib/modeldata/dmod/modeldata/datarequest/maas_data_catalog.py
  python/lib/modeldata/dmod/modeldata/datarequest/maas_data_catalog_reader.py
  python/services/datarequestservice/README.md
  python/services/datarequestservice/dmod/datarequestservice/__init__.py
  python/services/datarequestservice/dmod/datarequestservice/__main__.py
  python/services/datarequestservice/dmod/datarequestservice/_version.py
  python/services/datarequestservice/setup.py
Labels: enhancement

#113 Update ngen and ngen-deps Docker images
  docker/main/ngen/Dockerfile
  docker/main/ngen/deps/Dockerfile
Labels: bug

#115 Fix GUI code for comms package update
  python/gui/MaaS/cbv/DMODProxy.py
  python/gui/MaaS/cbv/EditView.py
Labels: bug
