Repository NOAA-OWP/DMOD, pull requests merged in 2023-07, with the labels that each got.

#365 Pin pydantic<2
  python/lib/communication/setup.py
  python/lib/core/setup.py
  python/lib/modeldata/setup.py
  python/lib/scheduler/setup.py
  python/services/dataservice/setup.py
  requirements.txt
Labels: maas

#366 Improve creation of ContinuousRestriction subtypes
  python/lib/core/dmod/core/meta_data.py
Labels: enhancement, maas

#367 Add data format value for t-route configs
  python/lib/core/dmod/core/meta_data.py
Labels: enhancement, maas

#373 Fix FastApi openapi spec enum doc generation
  python/lib/core/dmod/core/enum.py
Labels: bug, maas

#385 Forward Dataset field references to resolve DatasetManager type
  python/lib/core/dmod/core/dataset.py
Labels: bug, maas

#395 Move extra, test-specific layer of ngen worker Docker image
  docker/main/ngen/Dockerfile
Labels: enhancement, maas
