Repository NOAA-OWP/DMOD, pull requests merged in 2024-04, with the labels that each got.

#578 chore: remove unused imports across entire codebase
  python/lib/communication/dmod/communication/metadata_message.py
  python/lib/communication/dmod/communication/partition_request.py
  python/lib/communication/dmod/communication/registered/registered_interface.py
  python/lib/communication/dmod/communication/registered/registered_session.py
  python/lib/communication/dmod/communication/session.py
  python/lib/communication/dmod/test/test_decorated_interface.py
  python/lib/communication/dmod/test/test_partial_realization_config.py
  python/lib/communication/dmod/test/test_websocket_interface.py
  python/lib/core/dmod/core/common/collection.py
  python/lib/core/dmod/core/common/helper_functions.py
  python/lib/core/dmod/core/common/tasks.py
  python/lib/core/dmod/core/dataset.py
  python/lib/core/dmod/core/meta_data.py
  python/lib/evaluations/dmod/evaluations/crosswalk/retriever.py
  python/lib/evaluations/dmod/evaluations/evaluate.py
  python/lib/evaluations/dmod/evaluations/measurement_units.py
  python/lib/evaluations/dmod/evaluations/retrieval.py
  python/lib/evaluations/dmod/evaluations/threshold/disk.py
  python/lib/evaluations/dmod/evaluations/util.py
  python/lib/evaluations/dmod/evaluations/writing/__init__.py
  python/lib/evaluations/dmod/evaluations/writing/netcdf.py
  python/lib/externalrequests/dmod/externalrequests/duplex/actions/end.py
  python/lib/externalrequests/dmod/externalrequests/duplex/handler.py
  python/lib/externalrequests/dmod/externalrequests/duplex/repeat.py
  python/lib/externalrequests/dmod/externalrequests/duplex/types.py
  python/lib/externalrequests/dmod/externalrequests/evaluation_request_handler.py
  python/lib/externalrequests/dmod/externalrequests/model_exec_request_handler.py
  python/lib/externalrequests/dmod/test/it_model_exec_request_handler.py
  python/lib/metrics/dmod/metrics/scoring.py
  python/lib/metrics/dmod/metrics/threshold.py
  python/lib/monitor/dmod/test/it_que_monitor.py
  python/lib/scheduler/dmod/scheduler/scheduler.py
  python/services/datarequestservice/dmod/datarequestservice/__main__.py
  python/services/monitorservice/dmod/monitorservice/service.py
  python/services/requestservice/dmod/requestservice/service.py
  python/services/subsetservice/dmod/subsetservice/__main__.py
Labels: Low Priority

#580 chore: swap exit for sys.exit; fixes #571
  python/lib/client/dmod/client/__main__.py
  python/lib/evaluations/update_diagrams.py
  python/services/datarequestservice/dmod/datarequestservice/__main__.py
  python/services/evaluationservice/dmod/evaluationservice/evaluation_service/management/commands/templates.py
  python/services/evaluationservice/dmod/evaluationservice/runner.py
  python/services/partitionerservice/dmod/partitionerservice/__main__.py
  python/services/requestservice/dmod/requestservice/__main__.py
  python/services/schedulerservice/dmod/schedulerservice/__main__.py
  python/services/subsetservice/dmod/subsetservice/__main__.py
Labels: bug, Low Priority, Low Hanging Fruit

#585 Pinned versions of gunicorn and Django
  python/gui/dependencies.txt
  requirements.txt
Labels: good first issue, dependencies, Low Priority, Low Hanging Fruit
