Repository NOAA-OWP/DMOD, pull requests merged in 2024-05, with the labels that each got.

#597 Updated the Dockerfile for the gui app_server to include missing libraries
  docker/nwm_gui/app_server/Dockerfile
Labels: bug

#603 fix(test): run `TestEvaluate` from anywhere
  python/lib/evaluations/dmod/test/test_evaluate.py
Labels: bug

#610 Fix bug in dataservice use of obj store settings
  python/services/dataservice/dmod/dataservice/_version.py
  python/services/dataservice/dmod/dataservice/rest_service.py
Labels: bug, maas

#625 fix(scripts): support mac version of nproc
  scripts/create_env_config.sh
Labels: bug

#624 Fix ngen entrypoint script for geopackage hydrofabrics
  docker/main/ngen/funcs.sh
  docker/main/ngen/ngen_entrypoint.sh
Labels: bug, maas

#634 Fix resource config script for missing directory
  scripts/create_resources_config.sh
Labels: bug, maas

#635 Fixing docker-py dependencies
  python/lib/monitor/dmod/monitor/_version.py
  python/lib/monitor/setup.py
  python/lib/scheduler/dmod/scheduler/_version.py
  python/lib/scheduler/setup.py
  python/services/dataservice/dmod/dataservice/_version.py
  python/services/dataservice/setup.py
  python/services/monitorservice/dmod/monitorservice/_version.py
  python/services/monitorservice/setup.py
  python/services/partitionerservice/dmod/partitionerservice/_version.py
  python/services/partitionerservice/setup.py
  python/services/schedulerservice/dmod/schedulerservice/_version.py
  python/services/schedulerservice/setup.py
Labels: dependencies, maas

#641 Pin Redis service image to open-source version
  docker/main/docker-deploy.yml
Labels: dependencies, maas
